### ISSUE TITLE
Application calls to smartcontracts fail.

### ISSUE THREAD

**Issue by Sam2much96** [lucasvanmol/algodot#19]
I'm attempting making calls to a hosted smart contract on testnet with app id: 116639568 and transaction id: HMNGTWFPJ6RA4TD6K76WNMPXZ6BELMNQG7C5T7KT7MMU3YRS47NQ

its a simple counting smart contract that's meant to increase and decrease a global integer

My app call in algodot is : 

var optin_tx = yield (Algorand.algod.construct_app_call(params, '4KMRCP23JP4SM2L65WBLK6A3TPT723ILD27R7W755P7GAU5VCE7LJHAUEQ', 116639568,['4KMRCP23JP4SM2L65WBLK6A3TPT723ILD27R7W755P7GAU5VCE7LJHAUEQ'],["str:inc"],  PoolIntArray([0]),PoolIntArray([0]),[0],[0],[0,1],[0,1]), "completed")

but it returns an error. E 0:00:17.960   <unset>: gdnative-core: method panicked (check stderr for output)
  <C++ Source>  <unset>:0 @ <unset>()
  <Stack Trace> Wallet.gd:515 @ _process()

im using these instructions to Construct Application calls
    fn construct_app_call(
        &self,
        _owner: TRef<Node>,
        params: SuggestedTransactionParams,
        sender: Address,
        #[opt] app_id: Option<u64>,
        #[opt] accounts: Option<Vec<Address>>,
        #[opt] app_arguments: Option<VariantArray>, // array of PoolByteArrays. Could perhaps be changed directily to Option<Vec<Vec<u8>>>
        #[opt] foreign_apps: Option<Int32Array>,
        #[opt] foreign_assets: Option<Int32Array>,
        #[opt] approval_program: Option<Vec<u8>>,
        #[opt] clear_state_program: Option<Vec<u8>>,
        #[opt] global_state_schema: Option<(u64, u64)>,
        #[opt] local_state_schema: Option<(u64, u64)>,
        #[opt] extra_pages: Option<u32>,

 Any assistance on this would be appreciated.

**Comment by Sam2much96** [comment]
Full rust backtrace

Opt into Smartcontract---placeholder method
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', algodot/src/algod/mod.rs:296:28
stack backtrace:
   0:     0x7f102567f060 - std::backtrace_rs::backtrace::libunwind::trace::h83db09f97ba446e0
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f102567f060 - std::backtrace_rs::backtrace::trace_unsynchronized::hbc692a375382599a
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f102567f060 - std::sys_common::backtrace::_print_fmt::h5d9374f1dc540502
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f102567f060 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bc20029fef91d
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f102569e9fe - core::fmt::write::h3ff59c1e0cfd7af2
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f102567a645 - std::io::Write::write_fmt::h57bc84b9ab3e4292
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/io/mod.rs:1679:15
   6:     0x7f1025680893 - std::sys_common::backtrace::_print::h58613138e3b60a1b
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f1025680893 - std::sys_common::backtrace::print::h182e9bde2e8d07ea
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f1025680893 - std::panicking::default_hook::{{closure}}::h829771b46ce932f3
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/panicking.rs:267:22
   9:     0x7f102568057f - std::panicking::default_hook::h167447d609e3453b
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/panicking.rs:286:9
  10:     0x7f1025680f39 - std::panicking::rust_panic_with_hook::haa7a7aef616e6ae8
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/panicking.rs:669:13
  11:     0x7f1025680df1 - std::panicking::begin_panic_handler::{{closure}}::h54de542be25d3155
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/panicking.rs:558:13
  12:     0x7f102567f50c - std::sys_common::backtrace::__rust_end_short_backtrace::hea1b3383b55d28ea
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7f1025680b52 - rust_begin_unwind
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/std/src/panicking.rs:556:5
  14:     0x7f102541b2c3 - core::panicking::panic_fmt::h80842252f3e1148b
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/core/src/panicking.rs:142:14
  15:     0x7f102541b18d - core::panicking::panic::h307d56ec552a34a7
                               at /rustc/3f83906b30798bf61513fa340524cebf6676f9db/library/core/src/panicking.rs:48:5
  16:     0x7f1025485bb1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h83dc946a3e9b11b2
  17:     0x7f10254a80f1 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h10d84a236bea7312
  18:     0x7f102548d995 - <<algodot::algod::Algodot as gdnative_core::export::class::NativeClassMethods>::register::ThisMethod as gdnative_core::export::method::StaticArgsMethod<algodot::algod::Algodot>>::call::he94d4a4183a217b6
  19:     0x7f1025471890 - <gdnative_core::export::method::Stateless<F> as gdnative_core::export::method::Method<C>>::call::h77a1a2db1fa7390c
  20:     0x7f10254680b1 - std::panicking::try::he97af023da1cbc3c
  21:     0x7f10254764db - gdnative_core::export::method::method_wrapper::h9174c07347ca3cdb
  22:          0x1cc6135 - _ZN20NativeScriptInstance4callERK10StringNamePPK7VariantiRNS3_9CallErrorE
                               at /home/samuel/godot/modules/gdnative/nativescript/nativescript.cpp:731:29
  23:          0x479577f - _ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE
                               at /home/samuel/godot/core/object.cpp:899:30
  24:          0x483428d - _ZN7Variant8call_ptrERK10StringNamePPKS_iPS_RNS_9CallErrorE
                               at /home/samuel/godot/core/variant_call.cpp:1176:18
  25:          0x18f3b43 - _ZN16GDScriptFunction4callEP16GDScriptInstancePPK7VariantiRNS2_9CallErrorEPNS_9CallStateE
                               at /home/samuel/godot/modules/gdscript/gdscript_function.cpp:1044:20
  26:          0x18fa5fe - _ZN21GDScriptFunctionState6resumeERK7Variant
                               at /home/samuel/godot/modules/gdscript/gdscript_function.cpp:1810:63
  27:          0x18f9e7d - _ZN21GDScriptFunctionState16_signal_callbackEPPK7VariantiRNS0_9CallErrorE
                               at /home/samuel/godot/modules/gdscript/gdscript_function.cpp:1758:19
  28:          0x1902414 - _ZN16MethodBindVarArgI21GDScriptFunctionStateE4callEP6ObjectPPK7VariantiRNS4_9CallErrorE
                               at /home/samuel/godot/./core/method_bind.h:333:63
  29:          0x479589a - _ZN6Object4callERK10StringNamePPK7VariantiRNS3_9CallErrorE
                               at /home/samuel/godot/core/object.cpp:918:21
  30:          0x4797908 - _ZN6Object11emit_signalERK10StringNamePPK7Varianti
                               at /home/samuel/godot/core/object.cpp:1224:16
  31:          0x4797315 - _ZN6Object12_emit_signalEPPK7VariantiRNS0_9CallErrorE
                               at /home/samuel/godot/core/object.cpp:1156:13
  32:          0x47ac7a2 - _ZN16MethodBindVarArgI6ObjectE4callEPS0_PPK7VariantiRNS3_9CallErrorE
                               at /home/samuel/godot/./core/method_bind.h:333:63
  33:          0x1cbe9f4 - godot_method_bind_call
                               at /home/samuel/godot/modules/gdnative/gdnative/gdnative.cpp:81:21
  34:     0x7f1025655db4 - gdnative_bindings::icalls::icallvarargs__str::hcfb21e4ec3db0abc
  35:     0x7f1025645925 - gdnative_async::rt::func_state::resolve::h86fe318723c953a9
  36:     0x7f10256422df - gdnative_async::rt::Context::resolve::h4682592e65fc8750
  37:     0x7f10254437bf - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h35cdcb2fc6990461
  38:     0x7f1025464321 - tokio::runtime::task::core::CoreStage<T>::poll::h604a78c5032a9d9e
  39:     0x7f1025497c09 - tokio::runtime::task::harness::Harness<T,S>::poll::h387a1a317d3b92a9
  40:     0x7f102562e02e - std::thread::local::LocalKey<T>::with::hac175d940fcc58f0
  41:     0x7f10256378ba - tokio::task::local::LocalSet::tick::h43b8260b38eeec46
  42:     0x7f102545fe9f - std::thread::local::LocalKey<T>::with::h5f3504f7d98b5f82
  43:     0x7f102544ca23 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd8d0d3ebd42f2731
  44:     0x7f102545fc11 - std::thread::local::LocalKey<T>::with::h1205a82ccde59d8d
  45:     0x7f102546ddd6 - tokio::runtime::scheduler::current_thread::Context::enter::haf40db63837aaa63
  46:     0x7f1025482e1b - tokio::macros::scoped_tls::ScopedKey<T>::set::h1ad4797872363d3e
  47:     0x7f102546d9e6 - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::hce29e354fa2d25c7
  48:     0x7f102545977d - tokio::runtime::Runtime::block_on::hb457301de1b96c28
  49:     0x7f1025460017 - std::thread::local::LocalKey<T>::with::h88c5d6c939cabf8e
  50:     0x7f102544e184 - <<algodot::AsyncExecutorDriver as gdnative_core::export::class::NativeClassMethods>::register::ThisMethod as gdnative_core::export::method::StaticArgsMethod<algodot::AsyncExecutorDriver>>::call::hbae78f1a71d2b615
  51:     0x7f102546f925 - <gdnative_core::export::method::Stateless<F> as gdnative_core::export::method::Method<C>>::call::h0f54d16189fad22e
  52:     0x7f1025467601 - std::panicking::try::h8db70f0bb5cf3d32
  53:     0x7f1025474b7b - gdnative_core::export::method::method_wrapper::h31782f163e592f78
  54:          0x1cc6c2b - _ZN20NativeScriptInstance15call_multilevelERK10StringNamePPK7Varianti
                               at /home/samuel/godot/modules/gdnative/nativescript/nativescript.cpp:892:40
  55:          0x376b14a - _ZN4Node13_notificationEi
                               at /home/samuel/godot/scene/main/node.cpp:56:43
  56:          0x1852170 - _ZN4Node14_notificationvEib
                               at /home/samuel/godot/./scene/main/node.h:45:2
  57:          0x47959dd - _ZN6Object12notificationEib
                               at /home/samuel/godot/core/object.cpp:927:16
  58:          0x37a47cf - _ZN9SceneTree19_notify_group_pauseERK10StringNamei
                               at /home/samuel/godot/scene/main/scene_tree.cpp:990:18
  59:          0x37a21d2 - _ZN9SceneTree4idleEf
                               at /home/samuel/godot/scene/main/scene_tree.cpp:536:21
  60:          0x17f2988 - _ZN4Main9iterationEv
                               at /home/samuel/godot/main/main.cpp:2201:48
  61:          0x17b3de4 - _ZN6OS_X113runEv
                               at /home/samuel/godot/platform/x11/os_x11.cpp:3643:22
  62:          0x17a0a9b - main
                               at /home/samuel/godot/platform/x11/godot_x11.cpp:55:9
  63:     0x7f1066926d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  64:     0x7f1066926e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  65:          0x17a08be - _start
  66:                0x0 - <unknown>

**Comment by Sam2much96** [comment]
calling any valid construct_app_call() transaction breaks the code too

var optin_tx = yield (Algorand.algod.construct_app_call(params, '4KMRCP23JP4SM2L65WBLK6A3TPT723ILD27R7W755P7GAU5VCE7LJHAUEQ'), "completed")

**Comment by Sam2much96** [comment]
Making calls from algorand sandbox on testnet works, but using construct_app_call() method returns and error which i can't seem to figure out . Does it construnct a smart contract or does it make calls to hosted smartcontracts?

Edit: It does both but it's largely unimplemented in core.rs

**Comment by Sam2much96** [comment]
thread '<unnamed>' panicked at 'not yet implemented', core/src/core.rs:215:67

any info on this?

**Comment by Sam2much96** [comment]
I can use compile teal function to compile Teal argument calls to the Smart contract and pass them through Poolbyte arrays and Arrays in app call [reference reading materials](https://developer.algorand.org/docs/get-details/dapps/smart-contracts/apps/)

**Comment by Sam2much96** [comment]
> thread '' panicked at 'not yet implemented', core/src/core.rs:215:67
> 
> any info on this?

It calls a todo!() method. Question, Is app call implemented yet?

**Comment by Sam2much96** [comment]
Problems in Core.rs:

1. Application Call method is unimplemented in core.rs 215. It uses a todo!() method as a placeholder
2. Line 143 in Core.rs is, I assume, a simple state machine. It needs improvements to the logic.
3. TrasactionType::KeyRegistration, TransactionType::ApplicationCallTransaction(), TransactionType::AssetFreezeTransaction() are unimplemented.
4. Application call method pushes an error code in Line 546, as well as Asset Freeze method which used a todo!() placeholder method

**Comment by Sam2much96** [comment]
looking through [Algonaut's Documentation](https://docs.rs/algonaut_transaction/0.4.2/algonaut_transaction/transaction/struct.ApplicationCallTransaction.html), I will now attempt writing a simple rust program that successfully makes smart contract calls and attempt binding it to Algodot's gdnative class.

**Comment by Sam2much96** [comment]
Using this Working app call template from my [forked algonaut repository](https://github.com/Sam2much96/algonaut) i'll implement app calls in algodot_core. 

**How does App Calls work in Algonaut**
By compiling Algonaut transaction and App call rust modules into a rust program, application calls (Strings converted to Unsigned 8 bit integers) can be made to smart contracts. Integrating app calls into Algodot would require porting the required rust libraries to enable app calls and implement them into algodot_core.

**Comment by Sam2much96** [comment]
Question?
What's the Difference between (1) algonaut_transaction::transaction::ApplicationCallTransaction     and   (2) algonaut_transaction::builder::CallApplication  ?

(2) is a builder for (1)

**Comment by Sam2much96** [comment]
Core.rs TransactionType Algonaut documentation [here](https://docs.rs/algonaut_transaction/0.4.2/algonaut_transaction/transaction/enum.TransactionType.html)

**Comment by Sam2much96** [comment]
Done. Testing now. Would close issue soon after testing. 
P.S. The  application call method has been downgraded to only call applications, it doesn't update application or host applications in it's current form.

**Comment by Sam2much96** [comment]
First Successful App call [here](https://testnet.algoexplorer.io/tx/HMNGTWFPJ6RA4TD6K76WNMPXZ6BELMNQG7C5T7KT7MMU3YRS47NQ)

would be updating the source code so it's easier to read & closing this issue. P.S. I used chatGPT to debug Rust compiler and finish writing the App call method. AI >.
